import Head from "next/head";
import Nav from "@/components/Nav";
import Posts from "@/components/Posts";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Nav></Nav>
        <Posts></Posts>
      </div>
    </>
  );
};

export default Home;
